/** \file
 *  This OBJC source file was generated by $ANTLR version 3.2 Aug 11, 2010 15:16:47
 *
 *     -  From the grammar source file : SimpleC.g
 *     -                            On : 2010-08-11 17:06:37
 *     -                 for the lexer : SimpleCLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2010 Alan Condit
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// $ANTLR 3.2 Aug 11, 2010 15:16:47 SimpleC.g 2010-08-11 17:06:37

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#import "SimpleCLexer.h"
/* ----------------------------------------- */


/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

#pragma mark Cyclic DFA implementation start DFA4
@implementation DFA4
const static NSInteger dfa4_eot[33] =
    {-1,-1,-1,-1,-1,-1,-1,11,11,11,11,-1,-1,22,-1,-1,-1,11,11,11,11,-1,-1,
     27,28,11,11,-1,-1,31,32,-1,-1};
const static NSInteger dfa4_eof[33] =
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1};
const static unichar dfa4_min[33] =
    {9,0,0,0,0,0,0,111,110,104,111,0,0,61,0,0,0,114,116,97,105,0,0,48,48,
     114,100,0,0,48,48,0,0};
const static unichar dfa4_max[33] =
    {125,0,0,0,0,0,0,111,110,104,111,0,0,61,0,0,0,114,116,97,105,0,0,122,
     122,114,100,0,0,122,122,0,0};
const static NSInteger dfa4_accept[33] =
    {-1,1,2,3,4,5,6,-1,-1,-1,-1,11,12,-1,15,16,17,-1,-1,-1,-1,14,13,-1,-1,
     -1,-1,7,8,-1,-1,9,10};
const static NSInteger dfa4_special[33] =
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
     -1,-1,-1,-1,-1,-1,-1,-1,-1,-1};
const static NSInteger dfa4_transition[] = {};
const static NSInteger dfa4_transition0[] = {24};
const static NSInteger dfa4_transition1[] = {26};
const static NSInteger dfa4_transition2[] = {29};
const static NSInteger dfa4_transition3[] = {20};
const static NSInteger dfa4_transition4[] = {25};
const static NSInteger dfa4_transition5[] = {16, 16, -1, -1, 16, -1, -1, 
 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, 
 -1, -1, -1, -1, -1, -1, 2, 4, -1, 15, 3, -1, -1, -1, 12, 12, 12, 12, 12, 
 12, 12, 12, 12, 12, -1, 1, 14, 13, -1, -1, -1, 11, 11, 11, 11, 11, 11, 
 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
 11, 11, -1, -1, -1, -1, 11, -1, 11, 11, 9, 11, 11, 7, 11, 11, 8, 11, 11, 
 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 10, 11, 11, 11, 11, 5, -1, 6};
const static NSInteger dfa4_transition6[] = {21};
const static NSInteger dfa4_transition7[] = {11, 11, 11, 11, 11, 11, 11, 
 11, 11, 11, -1, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 
 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
 -1, -1, -1, -1, 11, -1, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11};
const static NSInteger dfa4_transition8[] = {18};
const static NSInteger dfa4_transition9[] = {19};
const static NSInteger dfa4_transition10[] = {23};
const static NSInteger dfa4_transition11[] = {17};
const static NSInteger dfa4_transition12[] = {30};


- (id) initWithRecognizer:(ANTLRBaseRecognizer *) theRecognizer
{
    if ((self = [super initWithRecognizer:theRecognizer]) != nil) {
        eot = dfa4_eot;
        eof = dfa4_eof;
        min = dfa4_min;
        max = dfa4_max;
        accept = dfa4_accept;
        special = dfa4_special;
        if (!(transition = calloc(33, sizeof(void*)))) {
            [self release];
            return nil;
        }
        transition[0] = dfa4_transition5;
        transition[1] = dfa4_transition;
        transition[2] = dfa4_transition;
        transition[3] = dfa4_transition;
        transition[4] = dfa4_transition;
        transition[5] = dfa4_transition;
        transition[6] = dfa4_transition;
        transition[7] = dfa4_transition11;
        transition[8] = dfa4_transition8;
        transition[9] = dfa4_transition9;
        transition[10] = dfa4_transition3;
        transition[11] = dfa4_transition;
        transition[12] = dfa4_transition;
        transition[13] = dfa4_transition6;
        transition[14] = dfa4_transition;
        transition[15] = dfa4_transition;
        transition[16] = dfa4_transition;
        transition[17] = dfa4_transition10;
        transition[18] = dfa4_transition0;
        transition[19] = dfa4_transition4;
        transition[20] = dfa4_transition1;
        transition[21] = dfa4_transition;
        transition[22] = dfa4_transition;
        transition[23] = dfa4_transition7;
        transition[24] = dfa4_transition7;
        transition[25] = dfa4_transition2;
        transition[26] = dfa4_transition12;
        transition[27] = dfa4_transition;
        transition[28] = dfa4_transition;
        transition[29] = dfa4_transition7;
        transition[30] = dfa4_transition7;
        transition[31] = dfa4_transition;
        transition[32] = dfa4_transition;
    }
    return self;
}

- (void) dealloc
{
    free(transition);
    [super dealloc];
}

- (NSString *) description
{
    return @"1:1: Tokens : ( T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | FOR | INT_TYPE | CHAR | VOID | ID | INT | EQ | EQEQ | LT | PLUS | WS );";
}


@end
#pragma mark Cyclic DFA implementation end DFA4



/** As per Terence: No returns for lexer rules!
#pragma mark Rule return scopes start
#pragma mark Rule return scopes end
*/
@implementation SimpleCLexer


+ (void) initialize
{
    [ANTLRBaseRecognizer setGrammarFileName:@"SimpleC.g"];
}

- (id) initWithCharStream:(id<ANTLRCharStream>)anInput
{
    if ((self = [super initWithCharStream:anInput State:[ANTLRRecognizerSharedState newANTLRRecognizerSharedStateWithRuleLen:18+1]]) != nil) {
        dfa4 = [[[DFA4 alloc] initWithRecognizer:self] retain];
    }
    return self;
}

- (void) dealloc
{
    [dfa4 release];
    [super dealloc];
}

+ (NSString *) tokenNameForType:(NSInteger)aTokenType
{
    return [[self getTokenNames] objectAtIndex:aTokenType];
}

// $ANTLR start "T__21"
- (void) mT__21
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = T__21;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:7:7: ( ';' ) // ruleBlockSingleAlt
        // SimpleC.g:7:9: ';' // alt
        {
        [self matchChar:';']; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end T__21

// $ANTLR start "T__22"
- (void) mT__22
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = T__22;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:8:7: ( '(' ) // ruleBlockSingleAlt
        // SimpleC.g:8:9: '(' // alt
        {
        [self matchChar:'(']; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end T__22

// $ANTLR start "T__23"
- (void) mT__23
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = T__23;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:9:7: ( ',' ) // ruleBlockSingleAlt
        // SimpleC.g:9:9: ',' // alt
        {
        [self matchChar:',']; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end T__23

// $ANTLR start "T__24"
- (void) mT__24
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = T__24;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:10:7: ( ')' ) // ruleBlockSingleAlt
        // SimpleC.g:10:9: ')' // alt
        {
        [self matchChar:')']; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end T__24

// $ANTLR start "T__25"
- (void) mT__25
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = T__25;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:11:7: ( '{' ) // ruleBlockSingleAlt
        // SimpleC.g:11:9: '{' // alt
        {
        [self matchChar:'{']; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end T__25

// $ANTLR start "T__26"
- (void) mT__26
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = T__26;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:12:7: ( '}' ) // ruleBlockSingleAlt
        // SimpleC.g:12:9: '}' // alt
        {
        [self matchChar:'}']; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end T__26

// $ANTLR start "FOR"
- (void) mFOR
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = FOR;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:91:5: ( 'for' ) // ruleBlockSingleAlt
        // SimpleC.g:91:7: 'for' // alt
        {
        [self matchString:@"for"]; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end FOR

// $ANTLR start "INT_TYPE"
- (void) mINT_TYPE
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = INT_TYPE;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:92:10: ( 'int' ) // ruleBlockSingleAlt
        // SimpleC.g:92:12: 'int' // alt
        {
        [self matchString:@"int"]; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end INT_TYPE

// $ANTLR start "CHAR"
- (void) mCHAR
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = CHAR;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:93:5: ( 'char' ) // ruleBlockSingleAlt
        // SimpleC.g:93:7: 'char' // alt
        {
        [self matchString:@"char"]; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end CHAR

// $ANTLR start "VOID"
- (void) mVOID
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = VOID;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:94:5: ( 'void' ) // ruleBlockSingleAlt
        // SimpleC.g:94:7: 'void' // alt
        {
        [self matchString:@"void"]; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end VOID

// $ANTLR start "ID"
- (void) mID
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = ID;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:96:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* ) // ruleBlockSingleAlt
        // SimpleC.g:96:9: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* // alt
        {
        if (([input LA:1]>='A' && [input LA:1]<='Z')||[input LA:1]=='_'||([input LA:1]>='a' && [input LA:1]<='z')) {
            [input consume];

        } else {
            ANTLRMismatchedSetException *mse = [ANTLRMismatchedSetException exceptionWithSet:nil stream:input];
            [self recover:mse];
            @throw mse;}
          /* element() */
        do {
            NSInteger alt1=2;
            {
                NSInteger LA1_0 = [input LA:1];
                if ( (LA1_0>='0' && LA1_0<='9')||(LA1_0>='A' && LA1_0<='Z')||LA1_0=='_'||(LA1_0>='a' && LA1_0<='z') ) {
                    alt1=1;
                }

            }
            switch (alt1) {
                case 1 :
                    // SimpleC.g: // alt
                    {
                    if (([input LA:1]>='0' && [input LA:1]<='9')||([input LA:1]>='A' && [input LA:1]<='Z')||[input LA:1]=='_'||([input LA:1]>='a' && [input LA:1]<='z')) {
                        [input consume];

                    } else {
                        ANTLRMismatchedSetException *mse = [ANTLRMismatchedSetException exceptionWithSet:nil stream:input];
                        [self recover:mse];
                        @throw mse;}
                      /* element() */
                     /* elements */
                    }
                    break;

                default :
                    goto loop1;
            }
        } while (YES);
        loop1: ;
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end ID

// $ANTLR start "INT"
- (void) mINT
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = INT;
        NSInteger _channel = ANTLRTokenChannelDefault;
        id<ANTLRToken> int=nil;
        List list_int=nil;
        // SimpleC.g:99:5: ( (int+= ( '0' .. '9' ) )+ ) // ruleBlockSingleAlt
        // SimpleC.g:99:7: (int+= ( '0' .. '9' ) )+ // alt
        {
        // SimpleC.g:99:10: (int+= ( '0' .. '9' ) )+ // positiveClosureBlock
        NSInteger cnt2=0;
        do {
            NSInteger alt2=2;
            {
                NSInteger LA2_0 = [input LA:1];
                if ( (LA2_0>='0' && LA2_0<='9') ) {
                    alt2=1;
                }

            }
            switch (alt2) {
                case 1 :
                    // SimpleC.g:99:10: int+= ( '0' .. '9' ) // alt
                    {
                    // SimpleC.g:99:12: ( '0' .. '9' ) // blockSingleAlt
                    // SimpleC.g:99:13: '0' .. '9' // alt
                    {
                    [self matchRangeFromChar:'0' to:'9'];   /* element() */
                     /* elements */
                    }
                      /* element() */
                     /* elements */
                    }
                    break;

                default :
                    if ( cnt2 >= 1 )
                        goto loop2;
                    ANTLREarlyExitException *eee = [ANTLREarlyExitException exceptionWithStream:input decisionNumber:2];
                    @throw eee;
            }
            cnt2++;
        } while (YES);
        loop2: ;
          /* element() */
        NSLog(@"%@", list_int);  /* element() */
         /* elements */
        }

        // token+rule list labels
        [list_int release];

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end INT

// $ANTLR start "EQ"
- (void) mEQ
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = EQ;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:102:6: ( '=' ) // ruleBlockSingleAlt
        // SimpleC.g:102:8: '=' // alt
        {
        [self matchChar:'=']; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end EQ

// $ANTLR start "EQEQ"
- (void) mEQEQ
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = EQEQ;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:103:6: ( '==' ) // ruleBlockSingleAlt
        // SimpleC.g:103:8: '==' // alt
        {
        [self matchString:@"=="]; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end EQEQ

// $ANTLR start "LT"
- (void) mLT
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = LT;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:104:6: ( '<' ) // ruleBlockSingleAlt
        // SimpleC.g:104:8: '<' // alt
        {
        [self matchChar:'<']; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end LT

// $ANTLR start "PLUS"
- (void) mPLUS
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = PLUS;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:105:6: ( '+' ) // ruleBlockSingleAlt
        // SimpleC.g:105:8: '+' // alt
        {
        [self matchChar:'+']; 
          /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end PLUS

// $ANTLR start "WS"
- (void) mWS
{
    //
    // This is not in the Java.stg

    @try {
        NSInteger _type = WS;
        NSInteger _channel = ANTLRTokenChannelDefault;
        // SimpleC.g:107:5: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ ) // ruleBlockSingleAlt
        // SimpleC.g:107:9: ( ' ' | '\\t' | '\\r' | '\\n' )+ // alt
        {
        // SimpleC.g:107:9: ( ' ' | '\\t' | '\\r' | '\\n' )+ // positiveClosureBlock
        NSInteger cnt3=0;
        do {
            NSInteger alt3=2;
            {
                NSInteger LA3_0 = [input LA:1];
                if ( (LA3_0>='\t' && LA3_0<='\n')||LA3_0=='\r'||LA3_0==' ' ) {
                    alt3=1;
                }

            }
            switch (alt3) {
                case 1 :
                    // SimpleC.g: // alt
                    {
                    if (([input LA:1]>='\t' && [input LA:1]<='\n')||[input LA:1]=='\r'||[input LA:1]==' ') {
                        [input consume];

                    } else {
                        ANTLRMismatchedSetException *mse = [ANTLRMismatchedSetException exceptionWithSet:nil stream:input];
                        [self recover:mse];
                        @throw mse;}
                      /* element() */
                     /* elements */
                    }
                    break;

                default :
                    if ( cnt3 >= 1 )
                        goto loop3;
                    ANTLREarlyExitException *eee = [ANTLREarlyExitException exceptionWithStream:input decisionNumber:3];
                    @throw eee;
            }
            cnt3++;
        } while (YES);
        loop3: ;
          /* element() */
         state.channel=99;   /* element() */
         /* elements */
        }

        // token+rule list labels

        [state setType:_type];

        state.channel = _channel;
    }
    @finally {
        //
    }
    return;
}
// $ANTLR end WS

- (void) mTokens
{
    // SimpleC.g:1:8: ( T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | FOR | INT_TYPE | CHAR | VOID | ID | INT | EQ | EQEQ | LT | PLUS | WS ) //ruleblock
    NSInteger alt4=17;
    alt4 = [dfa4 predict:input];
    switch (alt4) {
        case 1 :
            // SimpleC.g:1:10: T__21 // alt
            {
                [self mT__21];

              /* element() */
             /* elements */
            }
            break;
        case 2 :
            // SimpleC.g:1:16: T__22 // alt
            {
                [self mT__22];

              /* element() */
             /* elements */
            }
            break;
        case 3 :
            // SimpleC.g:1:22: T__23 // alt
            {
                [self mT__23];

              /* element() */
             /* elements */
            }
            break;
        case 4 :
            // SimpleC.g:1:28: T__24 // alt
            {
                [self mT__24];

              /* element() */
             /* elements */
            }
            break;
        case 5 :
            // SimpleC.g:1:34: T__25 // alt
            {
                [self mT__25];

              /* element() */
             /* elements */
            }
            break;
        case 6 :
            // SimpleC.g:1:40: T__26 // alt
            {
                [self mT__26];

              /* element() */
             /* elements */
            }
            break;
        case 7 :
            // SimpleC.g:1:46: FOR // alt
            {
                [self mFOR];

              /* element() */
             /* elements */
            }
            break;
        case 8 :
            // SimpleC.g:1:50: INT_TYPE // alt
            {
                [self mINT_TYPE];

              /* element() */
             /* elements */
            }
            break;
        case 9 :
            // SimpleC.g:1:59: CHAR // alt
            {
                [self mCHAR];

              /* element() */
             /* elements */
            }
            break;
        case 10 :
            // SimpleC.g:1:64: VOID // alt
            {
                [self mVOID];

              /* element() */
             /* elements */
            }
            break;
        case 11 :
            // SimpleC.g:1:69: ID // alt
            {
                [self mID];

              /* element() */
             /* elements */
            }
            break;
        case 12 :
            // SimpleC.g:1:72: INT // alt
            {
                [self mINT];

              /* element() */
             /* elements */
            }
            break;
        case 13 :
            // SimpleC.g:1:76: EQ // alt
            {
                [self mEQ];

              /* element() */
             /* elements */
            }
            break;
        case 14 :
            // SimpleC.g:1:79: EQEQ // alt
            {
                [self mEQEQ];

              /* element() */
             /* elements */
            }
            break;
        case 15 :
            // SimpleC.g:1:84: LT // alt
            {
                [self mLT];

              /* element() */
             /* elements */
            }
            break;
        case 16 :
            // SimpleC.g:1:87: PLUS // alt
            {
                [self mPLUS];

              /* element() */
             /* elements */
            }
            break;
        case 17 :
            // SimpleC.g:1:92: WS // alt
            {
                [self mWS];

              /* element() */
             /* elements */
            }
            break;

    }

}

@end // end of SimpleCLexer implementation

/* End of code
 * =============================================================================
 */
