/** \file
 *  This OBJC source file was generated by $ANTLR version ${project.version} ${buildNumber}
 *
 *     -  From the grammar source file : PolyDifferentiator.g
 *     -                            On : 2011-05-06 19:18:20
 *     -           for the tree parser : PolyDifferentiatorTreeParser
 *
 * Editing it, at least manually, is not wise.
 *
 * ObjC language generator and runtime by Alan Condit, acondit|hereisanat|ipns|dotgoeshere|com.
 *
 *
*/
// $ANTLR ${project.version} ${buildNumber} PolyDifferentiator.g 2011-05-06 19:18:20


/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#import "PolyDifferentiator.h"
/* ----------------------------------------- */


/* ============================================================================= */
/* =============================================================================
 * Start of recognizer
 */

#pragma mark Bitsets
static ANTLRBitSet *FOLLOW_8_in_poly44;
static const unsigned long long FOLLOW_8_in_poly44_data[] = { 0x0000000000000004LL};
static ANTLRBitSet *FOLLOW_poly_in_poly46;
static const unsigned long long FOLLOW_poly_in_poly46_data[] = { 0x0000000000000370LL};
static ANTLRBitSet *FOLLOW_poly_in_poly48;
static const unsigned long long FOLLOW_poly_in_poly48_data[] = { 0x0000000000000008LL};
static ANTLRBitSet *FOLLOW_MULT_in_poly55;
static const unsigned long long FOLLOW_MULT_in_poly55_data[] = { 0x0000000000000004LL};
static ANTLRBitSet *FOLLOW_INT_in_poly57;
static const unsigned long long FOLLOW_INT_in_poly57_data[] = { 0x0000000000000010LL};
static ANTLRBitSet *FOLLOW_ID_in_poly59;
static const unsigned long long FOLLOW_ID_in_poly59_data[] = { 0x0000000000000008LL};
static ANTLRBitSet *FOLLOW_MULT_in_poly71;
static const unsigned long long FOLLOW_MULT_in_poly71_data[] = { 0x0000000000000004LL};
static ANTLRBitSet *FOLLOW_INT_in_poly75;
static const unsigned long long FOLLOW_INT_in_poly75_data[] = { 0x0000000000000200LL};
static ANTLRBitSet *FOLLOW_9_in_poly78;
static const unsigned long long FOLLOW_9_in_poly78_data[] = { 0x0000000000000004LL};
static ANTLRBitSet *FOLLOW_ID_in_poly80;
static const unsigned long long FOLLOW_ID_in_poly80_data[] = { 0x0000000000000020LL};
static ANTLRBitSet *FOLLOW_INT_in_poly84;
static const unsigned long long FOLLOW_INT_in_poly84_data[] = { 0x0000000000000008LL};
static ANTLRBitSet *FOLLOW_9_in_poly122;
static const unsigned long long FOLLOW_9_in_poly122_data[] = { 0x0000000000000004LL};
static ANTLRBitSet *FOLLOW_ID_in_poly124;
static const unsigned long long FOLLOW_ID_in_poly124_data[] = { 0x0000000000000020LL};
static ANTLRBitSet *FOLLOW_INT_in_poly128;
static const unsigned long long FOLLOW_INT_in_poly128_data[] = { 0x0000000000000008LL};
static ANTLRBitSet *FOLLOW_INT_in_poly164;
static const unsigned long long FOLLOW_INT_in_poly164_data[] = { 0x0000000000000002LL};
static ANTLRBitSet *FOLLOW_ID_in_poly178;
static const unsigned long long FOLLOW_ID_in_poly178_data[] = { 0x0000000000000002LL};


#pragma mark Dynamic Global Scopes

#pragma mark Dynamic Rule Scopes

#pragma mark Rule Return Scopes start
@implementation PolyDifferentiator_poly_return /* returnScope */
/* AST returnScope.synthesize */
@synthesize tree; /* start of synthesize -- OBJC-Line 1837 */
+ (PolyDifferentiator_poly_return *)newPolyDifferentiator_poly_return
{
    return [[[PolyDifferentiator_poly_return alloc] init] retain];
}

- (id) init
{
    self = [super init];
    return self;
}

/* AST returnScope.methods */
- (ANTLRCommonTree *)getTree
{
    return tree;
}

- (void) setTree:(ANTLRCommonTree *)aTree
{
    if (tree != aTree) {
        if (tree != nil) [tree release];
        if (aTree != nil) [aTree retain];
        tree = aTree;
    }
}

- (void) dealloc
{
    self.tree = nil;
    [super dealloc];
}



@end /* end of returnScope implementation */


//#pragma mark Rule return scopes start
//

#pragma mark Rule return scopes start

@implementation PolyDifferentiator  // line 637

/* ObjC start of ruleAttributeScope */
#pragma mark Dynamic Rule Scopes
/* ObjC end of ruleAttributeScope */
#pragma mark global Attribute Scopes
/* ObjC start globalAttributeScope */
/* ObjC end globalAttributeScope */
/* ObjC start actions.(actionScope).synthesize */
/* ObjC end actions.(actionScope).synthesize */
/* ObjC start synthesize() */
/* AST genericParser.synthesize */
/* AST parserProperties */
@synthesize treeAdaptor;
/* ObjC end synthesize() */

+ (void) initialize
{
    #pragma mark Bitsets
    FOLLOW_8_in_poly44 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_8_in_poly44_data Count:(NSUInteger)1] retain];
    FOLLOW_poly_in_poly46 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_poly_in_poly46_data Count:(NSUInteger)1] retain];
    FOLLOW_poly_in_poly48 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_poly_in_poly48_data Count:(NSUInteger)1] retain];
    FOLLOW_MULT_in_poly55 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_MULT_in_poly55_data Count:(NSUInteger)1] retain];
    FOLLOW_INT_in_poly57 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_INT_in_poly57_data Count:(NSUInteger)1] retain];
    FOLLOW_ID_in_poly59 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_ID_in_poly59_data Count:(NSUInteger)1] retain];
    FOLLOW_MULT_in_poly71 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_MULT_in_poly71_data Count:(NSUInteger)1] retain];
    FOLLOW_INT_in_poly75 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_INT_in_poly75_data Count:(NSUInteger)1] retain];
    FOLLOW_9_in_poly78 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_9_in_poly78_data Count:(NSUInteger)1] retain];
    FOLLOW_ID_in_poly80 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_ID_in_poly80_data Count:(NSUInteger)1] retain];
    FOLLOW_INT_in_poly84 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_INT_in_poly84_data Count:(NSUInteger)1] retain];
    FOLLOW_9_in_poly122 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_9_in_poly122_data Count:(NSUInteger)1] retain];
    FOLLOW_ID_in_poly124 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_ID_in_poly124_data Count:(NSUInteger)1] retain];
    FOLLOW_INT_in_poly128 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_INT_in_poly128_data Count:(NSUInteger)1] retain];
    FOLLOW_INT_in_poly164 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_INT_in_poly164_data Count:(NSUInteger)1] retain];
    FOLLOW_ID_in_poly178 = [[ANTLRBitSet newANTLRBitSetWithBits:(const unsigned long long *)FOLLOW_ID_in_poly178_data Count:(NSUInteger)1] retain];

    [ANTLRBaseRecognizer setTokenNames:[[AMutableArray arrayWithObjects:@"<invalid>", @"<EOR>", @"<DOWN>", @"<UP>", 
 @"ID", @"INT", @"MULT", @"WS", @"'+'", @"'^'", nil] retain]];
    [ANTLRBaseRecognizer setGrammarFileName:@"PolyDifferentiator.g"];
}

+ (PolyDifferentiator *)newPolyDifferentiator:(id<ANTLRTreeNodeStream>)aStream
{
    return [[PolyDifferentiator alloc] initWithStream:aStream];


}

- (id) initWithStream:(id<ANTLRTreeNodeStream>)aStream
{
    self = [super initWithStream:aStream State:[[ANTLRRecognizerSharedState newANTLRRecognizerSharedStateWithRuleLen:1+1] retain]];
    if ( self != nil ) {


        /* start of actions-actionScope-init */
        /* start of init */
        /* AST genericParser.init */
        [self setTreeAdaptor:[[ANTLRCommonTreeAdaptor newTreeAdaptor] retain]];
    }
    return self;
}

- (void) dealloc
{
    /* AST genericParser.dealloc */
    [self setTreeAdaptor:nil];

    [super dealloc];
}

/* ObjC start members */
/* ObjC end members */
/* ObjC start actions.(actionScope).methods */
/* ObjC end actions.(actionScope).methods */
/* ObjC start methods() */
/* AST genericParser.methods */
/* AST parserMethods */
- (id<ANTLRTreeAdaptor>) getTreeAdaptor
{
	return treeAdaptor;
}

- (void) setTreeAdaptor:(id<ANTLRTreeAdaptor>)aTreeAdaptor
{
	if (aTreeAdaptor != treeAdaptor) {
		treeAdaptor = aTreeAdaptor;
	}
}
/* ObjC end methods() */
/* ObjC start rules */
/*
 * $ANTLR start poly
 * PolyDifferentiator.g:10:1: poly : ( ^( '+' poly poly ) | ^( MULT INT ID ) -> INT | ^( MULT c= INT ^( '^' ID e= INT ) ) -> ^( MULT[@\"*\"] INT[c2] ^( '^' ID INT[e2] ) ) | ^( '^' ID e= INT ) -> ^( MULT[@\"*\"] INT[c2] ^( '^' ID INT[e2] ) ) | INT -> INT[@\"0\"] | ID -> INT[@\"1\"] );
 */
- (PolyDifferentiator_poly_return *) poly
{
    /* my ruleScopeSetUp */
    /* Terence's stuff */

    /* ASTTreeParser ruleDeclarations */
    /* AST ruleDeclarations */
    PolyDifferentiator_poly_return * retval = [PolyDifferentiator_poly_return newPolyDifferentiator_poly_return];
    [retval setStart:[input LT:1]];


    ANTLRCommonTree *root_0 = nil;

    ANTLRCommonTree *_first_0 = nil;
    ANTLRCommonTree *_last = nil;

    @try {
        /* AST ruleLabelDefs */
        ANTLRCommonTree *c = nil;
        ANTLRCommonTree *e = nil;
        ANTLRCommonTree *char_literal1 = nil;
        ANTLRCommonTree *MULT4 = nil;
        ANTLRCommonTree *INT5 = nil;
        ANTLRCommonTree *ID6 = nil;
        ANTLRCommonTree *MULT7 = nil;
        ANTLRCommonTree *char_literal8 = nil;
        ANTLRCommonTree *ID9 = nil;
        ANTLRCommonTree *char_literal10 = nil;
        ANTLRCommonTree *ID11 = nil;
        ANTLRCommonTree *INT12 = nil;
        ANTLRCommonTree *ID13 = nil;
         PolyDifferentiator_poly_return * poly2 = nil ;
         
         PolyDifferentiator_poly_return * poly3 = nil ;
         

        ANTLRCommonTree *c_tree=nil;
        ANTLRCommonTree *e_tree=nil;
        ANTLRCommonTree *char_literal1_tree=nil;
        ANTLRCommonTree *MULT4_tree=nil;
        ANTLRCommonTree *INT5_tree=nil;
        ANTLRCommonTree *ID6_tree=nil;
        ANTLRCommonTree *MULT7_tree=nil;
        ANTLRCommonTree *char_literal8_tree=nil;
        ANTLRCommonTree *ID9_tree=nil;
        ANTLRCommonTree *char_literal10_tree=nil;
        ANTLRCommonTree *ID11_tree=nil;
        ANTLRCommonTree *INT12_tree=nil;
        ANTLRCommonTree *ID13_tree=nil;
        ANTLRRewriteRuleTokenStream *stream_INT =
            [[ANTLRRewriteRuleNodeStream newANTLRRewriteRuleNodeStream:treeAdaptor
                                                             description:@"token INT"] retain];
        ANTLRRewriteRuleTokenStream *stream_MULT =
            [[ANTLRRewriteRuleNodeStream newANTLRRewriteRuleNodeStream:treeAdaptor
                                                             description:@"token MULT"] retain];
        ANTLRRewriteRuleTokenStream *stream_ID =
            [[ANTLRRewriteRuleNodeStream newANTLRRewriteRuleNodeStream:treeAdaptor
                                                             description:@"token ID"] retain];
        ANTLRRewriteRuleTokenStream *stream_9 =
            [[ANTLRRewriteRuleNodeStream newANTLRRewriteRuleNodeStream:treeAdaptor
                                                             description:@"token 9"] retain];

        // PolyDifferentiator.g:10:5: ( ^( '+' poly poly ) | ^( MULT INT ID ) -> INT | ^( MULT c= INT ^( '^' ID e= INT ) ) -> ^( MULT[@\"*\"] INT[c2] ^( '^' ID INT[e2] ) ) | ^( '^' ID e= INT ) -> ^( MULT[@\"*\"] INT[c2] ^( '^' ID INT[e2] ) ) | INT -> INT[@\"0\"] | ID -> INT[@\"1\"] ) //ruleblock
        NSInteger alt1=6;
        unichar charLA1 = [input LA:1];
        switch (charLA1) {
            case 8: ;
                {
                alt1=1;
                }
                break;
            case MULT: ;
                {
                NSInteger LA1_2 = [input LA:2];

                if ( (LA1_2==DOWN) ) {
                    NSInteger LA1_6 = [input LA:3];

                    if ( (LA1_6==INT) ) {
                        NSInteger LA1_7 = [input LA:4];

                        if ( (LA1_7==ID) ) {
                            alt1=2;
                        }
                        else if ( (LA1_7==9) ) {
                            alt1=3;
                        }
                        else {
                            ANTLRNoViableAltException *nvae = [ANTLRNoViableAltException newException:1 state:7 stream:input];
                            nvae.c = LA1_7;
                            @throw nvae;

                        }
                    }
                    else {
                        ANTLRNoViableAltException *nvae = [ANTLRNoViableAltException newException:1 state:6 stream:input];
                        nvae.c = LA1_6;
                        @throw nvae;

                    }
                }
                else {
                    ANTLRNoViableAltException *nvae = [ANTLRNoViableAltException newException:1 state:2 stream:input];
                    nvae.c = LA1_2;
                    @throw nvae;

                }
                }
                break;
            case 9: ;
                {
                alt1=4;
                }
                break;
            case INT: ;
                {
                alt1=5;
                }
                break;
            case ID: ;
                {
                alt1=6;
                }
                break;

        default: ;
            ANTLRNoViableAltException *nvae = [ANTLRNoViableAltException newException:1 state:0 stream:input];
            nvae.c = charLA1;
            @throw nvae;

        }

        switch (alt1) {
            case 1 : ;
                // PolyDifferentiator.g:10:7: ^( '+' poly poly ) // alt
                {
                root_0 = (ANTLRCommonTree *)[[[treeAdaptor class] newEmptyTree] retain];


                /* ASTTreeParser tree */
                _last = (ANTLRCommonTree *)[input LT:1];
                {
                ANTLRCommonTree *_save_last_1 = _last;
                ANTLRCommonTree *_first_1 = nil;
                ANTLRCommonTree *root_1 = [[[treeAdaptor class] newEmptyTree] retain];
                /* ASTTreeParser tokenRefRuleRoot */
                _last = (ANTLRCommonTree *)[input LT:1];
                char_literal1=(ANTLRCommonTree *)[self match:input TokenType:8 Follow:FOLLOW_8_in_poly44]; 
                char_literal1_tree = (ANTLRCommonTree *)[treeAdaptor dupNode:char_literal1];


                root_1 = (ANTLRCommonTree *)[treeAdaptor becomeRoot:char_literal1_tree old:root_1];


                [self match:input TokenType:ANTLRTokenTypeDOWN Follow:nil]; 
                /* ASTTreeParser ruleRef */
                _last = (ANTLRCommonTree *)[input LT:1];
                /* ruleRef */
                [self pushFollow:FOLLOW_poly_in_poly46];
                poly2 = [self poly];

                [self popFollow];


                    [treeAdaptor addChild:poly2.tree toTree:root_1];


                /* ASTTreeParser ruleRef */
                _last = (ANTLRCommonTree *)[input LT:1];
                /* ruleRef */
                [self pushFollow:FOLLOW_poly_in_poly48];
                poly3 = [self poly];

                [self popFollow];


                    [treeAdaptor addChild:poly3.tree toTree:root_1];


                [self match:input TokenType:ANTLRTokenTypeUP Follow:nil]; 
                [treeAdaptor addChild:root_1 toTree:root_0];
                _last = _save_last_1;
                }


                /* ASTTreeParser noRewrite */

                }
                break;
            case 2 : ;
                // PolyDifferentiator.g:11:4: ^( MULT INT ID ) // alt
                {
                /* ASTTreeParser tree */
                _last = (ANTLRCommonTree *)[input LT:1];
                {
                ANTLRCommonTree *_save_last_1 = _last;
                ANTLRCommonTree *_first_1 = nil;
                ANTLRCommonTree *root_1 = [[[treeAdaptor class] newEmptyTree] retain];
                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                MULT4=(ANTLRCommonTree *)[self match:input TokenType:MULT Follow:FOLLOW_MULT_in_poly55];  
                    [stream_MULT addElement:MULT4];


                [self match:input TokenType:ANTLRTokenTypeDOWN Follow:nil]; 
                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                INT5=(ANTLRCommonTree *)[self match:input TokenType:INT Follow:FOLLOW_INT_in_poly57];  
                    [stream_INT addElement:INT5];


                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                ID6=(ANTLRCommonTree *)[self match:input TokenType:ID Follow:FOLLOW_ID_in_poly59];  
                    [stream_ID addElement:ID6];


                [self match:input TokenType:ANTLRTokenTypeUP Follow:nil]; 
                [treeAdaptor addChild:root_1 toTree:root_0];
                _last = _save_last_1;
                }


                // AST REWRITE
                // elements: INT
                // token labels: 
                // rule labels: retval
                // token list labels: 
                // rule list labels: 
                // wildcard labels: 
                retval.tree = root_0;

                ANTLRRewriteRuleSubtreeStream *stream_retval =
                    [[ANTLRRewriteRuleSubtreeStream newANTLRRewriteRuleSubtreeStream:treeAdaptor
                        description:@"token retval" element:retval!=nil?[retval getTree]:nil] retain];

                root_0 = (ANTLRCommonTree *)[[[treeAdaptor class] newEmptyTree] retain];

                // 11:20: -> INT
                {
                     // TODO: args: 
                    [treeAdaptor addChild:/* ASTTreeParser createRewriteNodeFromElement */
                    [stream_INT nextNode]
                     toTree:root_0];

                }


                retval.tree = root_0;


                }
                break;
            case 3 : ;
                // PolyDifferentiator.g:12:4: ^( MULT c= INT ^( '^' ID e= INT ) ) // alt
                {
                /* ASTTreeParser tree */
                _last = (ANTLRCommonTree *)[input LT:1];
                {
                ANTLRCommonTree *_save_last_1 = _last;
                ANTLRCommonTree *_first_1 = nil;
                ANTLRCommonTree *root_1 = [[[treeAdaptor class] newEmptyTree] retain];
                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                MULT7=(ANTLRCommonTree *)[self match:input TokenType:MULT Follow:FOLLOW_MULT_in_poly71];  
                    [stream_MULT addElement:MULT7];


                [self match:input TokenType:ANTLRTokenTypeDOWN Follow:nil]; 
                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                c=(ANTLRCommonTree *)[self match:input TokenType:INT Follow:FOLLOW_INT_in_poly75];  
                    [stream_INT addElement:c];


                /* ASTTreeParser tree */
                _last = (ANTLRCommonTree *)[input LT:1];
                {
                ANTLRCommonTree *_save_last_2 = _last;
                ANTLRCommonTree *_first_2 = nil;
                ANTLRCommonTree *root_2 = [[[treeAdaptor class] newEmptyTree] retain];
                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                char_literal8=(ANTLRCommonTree *)[self match:input TokenType:9 Follow:FOLLOW_9_in_poly78];  
                    [stream_9 addElement:char_literal8];


                [self match:input TokenType:ANTLRTokenTypeDOWN Follow:nil]; 
                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                ID9=(ANTLRCommonTree *)[self match:input TokenType:ID Follow:FOLLOW_ID_in_poly80];  
                    [stream_ID addElement:ID9];


                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                e=(ANTLRCommonTree *)[self match:input TokenType:INT Follow:FOLLOW_INT_in_poly84];  
                    [stream_INT addElement:e];


                [self match:input TokenType:ANTLRTokenTypeUP Follow:nil]; 
                [treeAdaptor addChild:root_2 toTree:root_1];
                _last = _save_last_2;
                }


                [self match:input TokenType:ANTLRTokenTypeUP Follow:nil]; 
                [treeAdaptor addChild:root_1 toTree:root_0];
                _last = _save_last_1;
                }



                		NSString *c2 = [NSString stringWithFormat:@"%d", (c!=nil?[c.text integerValue]:0)*(e!=nil?[e.text integerValue]:0)];
                		NSString *e2 = [NSString stringWithFormat:@"%d", (e!=nil?[e.text integerValue]:0)-1];
                		


                // AST REWRITE
                // elements: INT, ID, 9, MULT, INT
                // token labels: 
                // rule labels: retval
                // token list labels: 
                // rule list labels: 
                // wildcard labels: 
                retval.tree = root_0;

                ANTLRRewriteRuleSubtreeStream *stream_retval =
                    [[ANTLRRewriteRuleSubtreeStream newANTLRRewriteRuleSubtreeStream:treeAdaptor
                        description:@"token retval" element:retval!=nil?[retval getTree]:nil] retain];

                root_0 = (ANTLRCommonTree *)[[[treeAdaptor class] newEmptyTree] retain];

                // 17:8: -> ^( MULT[@\"*\"] INT[c2] ^( '^' ID INT[e2] ) )
                {
                    // PolyDifferentiator.g:17:11: ^( MULT[@\"*\"] INT[c2] ^( '^' ID INT[e2] ) )
                    {
                        ANTLRCommonTree *root_1 = (ANTLRCommonTree *)[[[treeAdaptor class] newEmptyTree] retain];
                        root_1 = (ANTLRCommonTree *)[treeAdaptor becomeRoot:
                                [treeAdaptor createTree:MULT FromToken:@"*" Text:@"MULT"]
                         old:root_1];

                        [treeAdaptor addChild:
                                [treeAdaptor createTree:INT FromToken:c2 Text:@"INT"]
                         toTree:root_1];

                        // PolyDifferentiator.g:17:32: ^( '^' ID INT[e2] )
                        {
                            ANTLRCommonTree *root_2 = (ANTLRCommonTree *)[[[treeAdaptor class] newEmptyTree] retain];
                            root_2 = (ANTLRCommonTree *)[treeAdaptor becomeRoot:/* ASTTreeParser createRewriteNodeFromElement */
                            [stream_9 nextNode]
                             old:root_2];

                             // TODO: args: 
                            [treeAdaptor addChild:/* ASTTreeParser createRewriteNodeFromElement */
                            [stream_ID nextNode]
                             toTree:root_2];

                            [treeAdaptor addChild:
                                    [treeAdaptor createTree:INT FromToken:e2 Text:@"INT"]
                             toTree:root_2];

                            [treeAdaptor addChild:root_2 toTree:root_1];
                        }

                        [treeAdaptor addChild:root_1 toTree:root_0];
                    }

                }


                retval.tree = root_0;


                }
                break;
            case 4 : ;
                // PolyDifferentiator.g:18:4: ^( '^' ID e= INT ) // alt
                {
                /* ASTTreeParser tree */
                _last = (ANTLRCommonTree *)[input LT:1];
                {
                ANTLRCommonTree *_save_last_1 = _last;
                ANTLRCommonTree *_first_1 = nil;
                ANTLRCommonTree *root_1 = [[[treeAdaptor class] newEmptyTree] retain];
                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                char_literal10=(ANTLRCommonTree *)[self match:input TokenType:9 Follow:FOLLOW_9_in_poly122];  
                    [stream_9 addElement:char_literal10];


                [self match:input TokenType:ANTLRTokenTypeDOWN Follow:nil]; 
                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                ID11=(ANTLRCommonTree *)[self match:input TokenType:ID Follow:FOLLOW_ID_in_poly124];  
                    [stream_ID addElement:ID11];


                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                e=(ANTLRCommonTree *)[self match:input TokenType:INT Follow:FOLLOW_INT_in_poly128];  
                    [stream_INT addElement:e];


                [self match:input TokenType:ANTLRTokenTypeUP Follow:nil]; 
                [treeAdaptor addChild:root_1 toTree:root_0];
                _last = _save_last_1;
                }



                		NSString *c2 = [NSString stringWithFormat:@"%d", (e!=nil?[e.text integerValue]:0)];
                		NSString *e2 = [NSString stringWithFormat:@"%d", (e!=nil?[e.text integerValue]:0)-1];
                		


                // AST REWRITE
                // elements: ID, INT, INT, 9
                // token labels: 
                // rule labels: retval
                // token list labels: 
                // rule list labels: 
                // wildcard labels: 
                retval.tree = root_0;

                ANTLRRewriteRuleSubtreeStream *stream_retval =
                    [[ANTLRRewriteRuleSubtreeStream newANTLRRewriteRuleSubtreeStream:treeAdaptor
                        description:@"token retval" element:retval!=nil?[retval getTree]:nil] retain];

                root_0 = (ANTLRCommonTree *)[[[treeAdaptor class] newEmptyTree] retain];

                // 23:8: -> ^( MULT[@\"*\"] INT[c2] ^( '^' ID INT[e2] ) )
                {
                    // PolyDifferentiator.g:23:11: ^( MULT[@\"*\"] INT[c2] ^( '^' ID INT[e2] ) )
                    {
                        ANTLRCommonTree *root_1 = (ANTLRCommonTree *)[[[treeAdaptor class] newEmptyTree] retain];
                        root_1 = (ANTLRCommonTree *)[treeAdaptor becomeRoot:
                                [treeAdaptor createTree:MULT FromToken:@"*" Text:@"MULT"]
                         old:root_1];

                        [treeAdaptor addChild:
                                [treeAdaptor createTree:INT FromToken:c2 Text:@"INT"]
                         toTree:root_1];

                        // PolyDifferentiator.g:23:32: ^( '^' ID INT[e2] )
                        {
                            ANTLRCommonTree *root_2 = (ANTLRCommonTree *)[[[treeAdaptor class] newEmptyTree] retain];
                            root_2 = (ANTLRCommonTree *)[treeAdaptor becomeRoot:/* ASTTreeParser createRewriteNodeFromElement */
                            [stream_9 nextNode]
                             old:root_2];

                             // TODO: args: 
                            [treeAdaptor addChild:/* ASTTreeParser createRewriteNodeFromElement */
                            [stream_ID nextNode]
                             toTree:root_2];

                            [treeAdaptor addChild:
                                    [treeAdaptor createTree:INT FromToken:e2 Text:@"INT"]
                             toTree:root_2];

                            [treeAdaptor addChild:root_2 toTree:root_1];
                        }

                        [treeAdaptor addChild:root_1 toTree:root_0];
                    }

                }


                retval.tree = root_0;


                }
                break;
            case 5 : ;
                // PolyDifferentiator.g:24:4: INT // alt
                {
                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                INT12=(ANTLRCommonTree *)[self match:input TokenType:INT Follow:FOLLOW_INT_in_poly164];  
                    [stream_INT addElement:INT12];


                // AST REWRITE
                // elements: INT
                // token labels: 
                // rule labels: retval
                // token list labels: 
                // rule list labels: 
                // wildcard labels: 
                retval.tree = root_0;

                ANTLRRewriteRuleSubtreeStream *stream_retval =
                    [[ANTLRRewriteRuleSubtreeStream newANTLRRewriteRuleSubtreeStream:treeAdaptor
                        description:@"token retval" element:retval!=nil?[retval getTree]:nil] retain];

                root_0 = (ANTLRCommonTree *)[[[treeAdaptor class] newEmptyTree] retain];

                // 24:12: -> INT[@\"0\"]
                {
                    [treeAdaptor addChild:
                            [treeAdaptor createTree:INT FromToken:@"0" Text:@"INT"]
                     toTree:root_0];

                }


                retval.tree = root_0;


                }
                break;
            case 6 : ;
                // PolyDifferentiator.g:25:4: ID // alt
                {
                /* ASTTreeParser tokenRefBang */
                _last = (ANTLRCommonTree *)[input LT:1];
                ID13=(ANTLRCommonTree *)[self match:input TokenType:ID Follow:FOLLOW_ID_in_poly178];  
                    [stream_ID addElement:ID13];


                // AST REWRITE
                // elements: 
                // token labels: 
                // rule labels: retval
                // token list labels: 
                // rule list labels: 
                // wildcard labels: 
                retval.tree = root_0;

                ANTLRRewriteRuleSubtreeStream *stream_retval =
                    [[ANTLRRewriteRuleSubtreeStream newANTLRRewriteRuleSubtreeStream:treeAdaptor
                        description:@"token retval" element:retval!=nil?[retval getTree]:nil] retain];

                root_0 = (ANTLRCommonTree *)[[[treeAdaptor class] newEmptyTree] retain];

                // 25:11: -> INT[@\"1\"]
                {
                    [treeAdaptor addChild:
                            [treeAdaptor createTree:INT FromToken:@"1" Text:@"INT"]
                     toTree:root_0];

                }


                retval.tree = root_0;


                }
                break;

        }
        /* ASTTreeParser ruleCleanUp */
        /* AST ruleCleanUp */
        // token+rule list labels

        [stream_INT release];
        [stream_MULT release];
        [stream_ID release];
        [stream_9 release];

        retval.tree = (ANTLRCommonTree *)[treeAdaptor rulePostProcessing:root_0];

    }
    @catch (ANTLRRecognitionException *re) {
        [self reportError:re];
        [self recover:input Exception:re];
    }

    @finally {
        /* Terence's stuff */

    }
    return retval;
}
/* $ANTLR end poly */
/* ObjC end rules */

@end /* end of PolyDifferentiator implementation line 692 */
